apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: atfj0lt56-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: atfj0lt56-nodejs 
  name: atfj0lt56-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: atfj0lt56-nodejs 
